<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(CaptureTargetFramework)' == ''">net10.0-windows</TargetFramework>
    <TargetFramework Condition="'$(CaptureTargetFramework)' != ''">$(CaptureTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseWPF>true</UseWPF>
    <UseAppHost>true</UseAppHost>
    <LangVersion>10</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
