<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskOTime.DataLayer\TaskOTime.DataLayer.csproj" />
    <ProjectReference Include="..\TaskOTime.DTOs\TaskOTime.DTOs.csproj" />
  </ItemGroup>

</Project>
