using System.Collections.Immutable;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace Modernization.Analyzers.Tests;

internal sealed class InputFile(string path, string text) : AdditionalText
{
    public override string Path { get; } = path;
    public override SourceText GetText(CancellationToken cancellationToken = default) => SourceText.From(text);
}

internal sealed record AssessmentProject(string Path, Compilation Compilation, bool Tooling = false,
    bool Test = false, string[]? GeneratedPaths = null);

public sealed record CriterionMetric(int Examined, int Satisfied, int Unverified, int Diagnostics);

internal static class Evidence
{
    private static readonly System.Runtime.CompilerServices.ConditionalWeakTable<Compilation,
        System.Collections.Concurrent.ConcurrentDictionary<SyntaxTree, SemanticModel>> Models = new();
    internal static SemanticModel Model(Compilation c, SyntaxTree tree) =>
        Models.GetValue(c, _ => new()).GetOrAdd(tree, t => c.GetSemanticModel(t));
    internal static IEnumerable<INamedTypeSymbol> Types(Compilation c) => new PresentationScope(c).Types;
    internal static IEnumerable<ISymbol> Members(Compilation c) =>
        Types(c).SelectMany(t => t.GetMembers().Prepend(t));
    internal static bool Generated(SyntaxTree tree, AssessmentProject? project = null)
    {
        var file = System.IO.Path.GetFileName(tree.FilePath);
        return project?.GeneratedPaths?.Contains(tree.FilePath, StringComparer.OrdinalIgnoreCase) == true ||
            Regex.IsMatch(tree.FilePath, @"[\\/](obj|bin|Generated)[\\/]", RegexOptions.IgnoreCase) ||
            Regex.IsMatch(file, @"\.(g|g\.i|designer|AssemblyInfo)\.(cs|vb)$", RegexOptions.IgnoreCase) ||
            tree.GetRoot().GetLeadingTrivia().Any(t => t.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase));
    }
    internal static bool Source(ISymbol s, AssessmentProject p) =>
        s.Locations.Any(l => l.SourceTree is { } tree && !Generated(tree, p)) && !s.IsImplicitlyDeclared;
    internal static IEnumerable<IOperation> Operations(Compilation c, bool generated = false, AssessmentProject? p = null)
    {
        foreach (var tree in c.SyntaxTrees.Where(t => generated || !Generated(t, p)))
        {
            var model = Model(c, tree);
            var seen = new HashSet<IOperation>(ReferenceEqualityComparer.Instance);
            foreach (var node in tree.GetRoot().DescendantNodes())
                if (model.GetOperation(node) is { Parent: null } op)
                    foreach (var child in Descendants(op))
                        if (seen.Add(child)) yield return child;
        }
    }
    internal static IEnumerable<IOperation> Descendants(IOperation op)
    {
        yield return op;
        foreach (var child in op.ChildOperations)
            foreach (var nested in Descendants(child)) yield return nested;
    }
    internal static bool Implements(INamedTypeSymbol t, string name) =>
        t.AllInterfaces.Any(i => i.OriginalDefinition.ToDisplayString() == name);
    internal static bool Observable(INamedTypeSymbol t) => Implements(t, "System.ComponentModel.INotifyPropertyChanged");
    internal static bool Derives(INamedTypeSymbol? t, string name)
    {
        for (; t != null; t = t.BaseType) if (t.ToDisplayString() == name) return true;
        return false;
    }
    internal static Location At(ISymbol s) => s.Locations.FirstOrDefault(l => l.IsInSource) ?? Location.None;
    internal static XDocument Xml(AdditionalText file) =>
        XDocument.Load(XmlReader.Create(new StringReader(file.GetText()!.ToString()),
            new XmlReaderSettings { DtdProcessing = DtdProcessing.Prohibit, XmlResolver = null }), LoadOptions.SetLineInfo);
    internal static Location At(AdditionalText file, XObject? node = null)
    {
        var text = file.GetText()!;
        var info = node as IXmlLineInfo;
        var line = Math.Clamp((info?.HasLineInfo() == true ? info.LineNumber : 1) - 1, 0, text.Lines.Count - 1);
        var column = Math.Clamp((info?.HasLineInfo() == true ? info.LinePosition : 1) - 1, 0, text.Lines[line].Span.Length);
        var offset = text.Lines[line].Start + column;
        return Location.Create(file.Path, new TextSpan(offset, 0), new LinePositionSpan(new(line, column), new(line, column)));
    }
    internal static bool MasterData(string? value)
    {
        if (string.IsNullOrEmpty(value)) return false;
        var tokens = Regex.Replace(value, @"(\p{Ll}|\d)(\p{Lu})", "$1 $2");
        tokens = Regex.Replace(tokens, @"(\p{Lu})(\p{Lu}\p{Ll})", "$1 $2");
        return Regex.IsMatch(tokens, @"(?i)(?<!\p{L})master[\s_-]*data(?!\p{L})");
    }
    internal static bool Prose(string value)
    {
        var visible = Regex.Replace(value, @"\{[^{}]*\}", "");
        return Regex.IsMatch(visible, @"\p{L}{2,}") &&
            !Regex.IsMatch(visible.Trim(), @"^(?:[dDfFgGMmOoRrsStuUyY]|[HNnFfPpXx]\d|[dMyHhms:/.\s\\-]+)$") &&
            !Uri.TryCreate(visible, UriKind.Absolute, out _);
    }
}

// Bounded producer tracing, not arbitrary interprocedural execution. It follows source
// getters, field/local assignments and parameter arguments; it deliberately ignores names.
internal sealed class Producers(Compilation compilation, IOperation[] operations, bool dataOnly = false)
{
    private readonly Dictionary<ISymbol, List<IOperation>> definitions = Index(operations);
    private readonly Dictionary<ISymbol, List<IOperation>> returns = ReturnIndex(compilation, operations);
    internal static ISymbol? ReturnOwner(Compilation compilation, IOperation operation)
    {
        var symbol = Evidence.Model(compilation, operation.Syntax.SyntaxTree).GetEnclosingSymbol(operation.Syntax.SpanStart);
        return (symbol as IMethodSymbol)?.AssociatedSymbol ?? symbol;
    }
    private static Dictionary<ISymbol, List<IOperation>> ReturnIndex(Compilation compilation, IOperation[] operations)
    {
        var result = new Dictionary<ISymbol, List<IOperation>>(SymbolEqualityComparer.Default);
        foreach (var operation in operations.OfType<IReturnOperation>())
        {
            if (operation.ReturnedValue == null || ReturnOwner(compilation, operation) is not { } symbol) continue;
            if (!result.TryGetValue(symbol, out var values)) result.Add(symbol, values = []);
            values.Add(operation.ReturnedValue);
        }
        return result;
    }
    private static Dictionary<ISymbol, List<IOperation>> Index(IOperation[] operations)
    {
        var result = new Dictionary<ISymbol, List<IOperation>>(SymbolEqualityComparer.Default);
        void Add(ISymbol? symbol, IOperation? value)
        {
            if (symbol == null || value == null) return;
            if (!result.TryGetValue(symbol, out var values)) result.Add(symbol, values = []);
            values.Add(value);
        }
        foreach (var op in operations)
        {
            if (op is ISimpleAssignmentOperation a) Add(Target(a.Target), a.Value);
            if (op is IArgumentOperation arg) Add(arg.Parameter, arg.Value);
            if (op is IVariableDeclaratorOperation v) Add(v.Symbol, v.Initializer?.Value);
            if (op is IVariableDeclarationOperation declaration)
                foreach (var declarator in declaration.Declarators) Add(declarator.Symbol, declaration.Initializer?.Value);
            if (op is IFieldInitializerOperation f)
                foreach (var field in f.InitializedFields) Add(field, f.Value);
            if (op is IPropertyInitializerOperation p)
                foreach (var property in p.InitializedProperties) Add(property, p.Value);
        }
        return result;
    }
    internal IEnumerable<IOperation> Of(IOperation operation) => Walk(operation, new HashSet<ISymbol>(SymbolEqualityComparer.Default), 0);
    private IEnumerable<IOperation> Walk(IOperation operation, HashSet<ISymbol> seen, int depth)
    {
        if (depth > 32 || operation is INameOfOperation) yield break;
        yield return operation;
        ISymbol? symbol = operation switch
        {
            ILocalReferenceOperation l => l.Local,
            IFieldReferenceOperation f => f.Field,
            IPropertyReferenceOperation p => p.Property,
            IParameterReferenceOperation p => p.Parameter,
            IInvocationOperation i when i.TargetMethod.Locations.Any(l => l.IsInSource) => i.TargetMethod,
            _ => null
        };
        foreach (var child in Children(operation))
            foreach (var value in Walk(child, seen, depth + 1)) yield return value;
        if (symbol == null || !seen.Add(symbol)) yield break;
        if (dataOnly)
        {
            foreach (var returned in returns.GetValueOrDefault(symbol) ?? [])
                foreach (var value in Walk(returned, seen, depth + 1)) yield return value;
        }
        foreach (var declaration in dataOnly ? [] : symbol.DeclaringSyntaxReferences)
        {
            var syntax = declaration.GetSyntax();
            var model = Evidence.Model(compilation, syntax.SyntaxTree);
            // VB symbol declarations point to the statement, not its enclosing block.
            if (syntax.Language == LanguageNames.VisualBasic && syntax.Parent?.GetType().Name is
                "PropertyBlockSyntax" or "MethodBlockSyntax" or "ConstructorBlockSyntax")
                syntax = syntax.Parent;
            foreach (var node in syntax.DescendantNodesAndSelf())
                if (model.GetOperation(node) is IReturnOperation { ReturnedValue: { } returned })
                    foreach (var value in Walk(returned, seen, depth + 1)) yield return value;
                else if (model.GetOperation(node) is IVariableInitializerOperation init)
                    foreach (var value in Walk(init.Value, seen, depth + 1)) yield return value;
                else if (model.GetOperation(node) is IPropertyInitializerOperation pi)
                    foreach (var value in Walk(pi.Value, seen, depth + 1)) yield return value;
                else if (model.GetOperation(node) is IFieldInitializerOperation fi)
                    foreach (var value in Walk(fi.Value, seen, depth + 1)) yield return value;
        }
        foreach (var source in definitions.GetValueOrDefault(symbol) ?? [])
        {
            foreach (var value in Walk(source, seen, depth + 1)) yield return value;
        }
    }
    private IEnumerable<IOperation> Children(IOperation operation)
    {
        if (!dataOnly) return operation.ChildOperations;
        if (operation is IConditionalOperation conditional)
            return new[] { conditional.WhenTrue, conditional.WhenFalse }.OfType<IOperation>();
        if (operation is ISwitchExpressionOperation expression) return expression.Arms.Select(a => a.Value);
        if (operation is IPropertyReferenceOperation or IFieldReferenceOperation or IObjectCreationOperation) return [];
        if (operation is IInvocationOperation call)
        {
            if (call.TargetMethod.Locations.Any(l => l.IsInSource)) return [];
            if (call.TargetMethod.ContainingType.SpecialType == SpecialType.System_String)
                return (call.Instance == null ? [] : new[] { call.Instance }).Concat(
                    call.Arguments.Where(a => a.Parameter?.Type.ToDisplayString() != "System.IFormatProvider")
                        .Select(a => a.Value));
            // A lookup/format/provider argument is not the returned presentation value.
            return [];
        }
        if (operation.Type?.SpecialType == SpecialType.System_Boolean) return [];
        return operation.ChildOperations;
    }
    private static ISymbol? Target(IOperation op) => op switch
    {
        ILocalReferenceOperation l => l.Local, IFieldReferenceOperation f => f.Field,
        IPropertyReferenceOperation p => p.Property, _ => null
    };
}
