<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseAppHost>true</UseAppHost>
    <StartupObject>TaskOTime.Theme.TestHost.Program</StartupObject>
    <RootNamespace></RootNamespace>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <OptionStrict>On</OptionStrict>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaskOTime.App\TaskOTime.App.csproj" />
    <ProjectReference Include="..\TaskOTime.ViewModel\TaskOTime.ViewModel.csproj" />
    <ProjectReference Include="..\TaskOTime.TimeTrackingServices.Tests\TestDoubles\TaskOTime.TimeTrackingServices.TestDoubles.csproj" />
  </ItemGroup>
</Project>
