//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOTime.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TaskOTime.DTOs;
    
    public partial class TaskOTimeContext : DbContext
    {
        public TaskOTimeContext()
            : base("name=TaskOTimeContext")
        {
            ConfigureContext();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategorySymbol> CategorySymbol { get; set; }
        public virtual DbSet<GuidReservation> GuidReservation { get; set; }
        public virtual DbSet<LogItem> LogItem { get; set; }
        public virtual DbSet<LookupItem> LookupItem { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<SharableProject> SharableProject { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TaskItem> TaskItem { get; set; }
        public virtual DbSet<TaskList> TaskList { get; set; }
        public virtual DbSet<TenantLead> TenantLead { get; set; }
        public virtual DbSet<TimeItem> TimeItem { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WebLink> WebLink { get; set; }
    }
}
