//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOTime.App.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RestoreMainWindowPlacement
        {
            get { return ((bool)(this["RestoreMainWindowPlacement"])); }
            set { this["RestoreMainWindowPlacement"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double MainWindowLeft
        {
            get { return ((double)(this["MainWindowLeft"])); }
            set { this["MainWindowLeft"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double MainWindowTop
        {
            get { return ((double)(this["MainWindowTop"])); }
            set { this["MainWindowTop"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1120")]
        public double MainWindowWidth
        {
            get { return ((double)(this["MainWindowWidth"])); }
            set { this["MainWindowWidth"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("760")]
        public double MainWindowHeight
        {
            get { return ((double)(this["MainWindowHeight"])); }
            set { this["MainWindowHeight"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaturdayIsWorkday
        {
            get { return ((bool)(this["SaturdayIsWorkday"])); }
            set { this["SaturdayIsWorkday"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SundayIsWorkday
        {
            get { return ((bool)(this["SundayIsWorkday"])); }
            set { this["SundayIsWorkday"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int BookedDateRangeCount
        {
            get { return ((int)(this["BookedDateRangeCount"])); }
            set { this["BookedDateRangeCount"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tage")]
        public string BookedDateRangeUnit
        {
            get { return ((string)(this["BookedDateRangeUnit"])); }
            set { this["BookedDateRangeUnit"] = value; }
        }
    }
}
