<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskOTime.DTOs\TaskOTime.DTOs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TaskOTime.AppServer\Models\*.cs" LinkBase="AppServer\Models" />
    <Compile Include="..\TaskOTime.AppServer\Services\AdminMainDataService.cs" Link="AppServer\Services\AdminMainDataService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\AnalysisService.cs" Link="AppServer\Services\AnalysisService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\ApplicationServiceBase.cs" Link="AppServer\Services\ApplicationServiceBase.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\IAdminMainDataService.cs" Link="AppServer\Services\IAdminMainDataService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\IAnalysisService.cs" Link="AppServer\Services\IAnalysisService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\ITimeBookingService.cs" Link="AppServer\Services\ITimeBookingService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\TimeBookingService.cs" Link="AppServer\Services\TimeBookingService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\IUserAdministrationService.cs" Link="AppServer\Services\IUserAdministrationService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\UserAdministrationService.cs" Link="AppServer\Services\UserAdministrationService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\IAuthenticationService.cs" Link="AppServer\Services\IAuthenticationService.cs" />
    <Compile Include="..\TaskOTime.AppServer\Services\AuthenticationService.cs" Link="AppServer\Services\AuthenticationService.cs" />
    <Compile Include="..\TaskOTime.ViewModel\Base\ViewModelBase.cs" Link="ViewModel\Base\ViewModelBase.cs" />
    <Compile Include="..\TaskOTime.ViewModel\Base\DelegateCommand.cs" Link="ViewModel\Base\DelegateCommand.cs" />
    <Compile Include="..\TaskOTime.ViewModel\IMaintenanceInteraction.cs" Link="ViewModel\IMaintenanceInteraction.cs" />
    <Compile Include="..\TaskOTime.ViewModel\ServiceWorkspace.cs" Link="ViewModel\ServiceWorkspace.cs" />
    <Compile Include="..\TaskOTime.ViewModel\ViewModels\MaintenanceViewModel.cs" Link="ViewModel\ViewModels\MaintenanceViewModel.cs" />
    <Compile Include="..\TaskOTime.ViewModel\ViewModels\TenantUserViewModel.cs" Link="ViewModel\ViewModels\TenantUserViewModel.cs" />
    <Compile Include="..\TaskOTime.ViewModel\ViewModels\MainDataViewModel.cs" Link="ViewModel\ViewModels\MainDataViewModel.cs" />
    <Compile Include="..\TaskOTime.ViewModel\ViewModels\ProjectViewModel.cs" Link="ViewModel\ViewModels\ProjectViewModel.cs" />
    <Compile Include="..\TaskOTime.ViewModel\ViewModels\MasterTaskViewModel.cs" Link="ViewModel\ViewModels\MasterTaskViewModel.cs" />
    <Compile Include="..\TaskOTime.ViewModel\ViewModels\CollaborationViewModel.cs" Link="ViewModel\ViewModels\CollaborationViewModel.cs" />
    <Compile Include="..\TaskOTime.AppServer\Security\*.cs" LinkBase="AppServer\Security" />
    <Compile Include="..\TaskOTime.AppServer\TimeBooking\*.cs" LinkBase="AppServer\TimeBooking" />
    <Compile Include="..\TaskOTime.DataLayer\Model\TaskOTime.Context.cs" Link="DataLayer\Model\TaskOTime.Context.cs" />
    <Compile Include="..\TaskOTime.DataLayer\SystemTimeMarkerSeed.cs" Link="DataLayer\SystemTimeMarkerSeed.cs" />
    <Compile Include="..\TaskOTime.DataLayer\TaskOTimeContext.partial.cs" Link="DataLayer\TaskOTimeContext.partial.cs" />
    <Compile Include="..\TaskOTime.DataLayer\TaskOTimeContextFactory.cs" Link="DataLayer\TaskOTimeContextFactory.cs" />
  </ItemGroup>

  <ItemGroup>
    <EntityDeploy Include="..\TaskOTime.DataLayer\Model\TaskOTime.edmx" Link="Model\TaskOTime.edmx" />
    <None Include="..\TaskOTime.DataLayer\DbGenerationScript.sql" Link="DbGenerationScript.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="CopyDataLayerMetadata" AfterTargets="Build">
    <ItemGroup>
      <TaskOTimeDataLayerMetadata Include="..\TaskOTime.DataLayer\bin\$(Configuration)\Model\TaskOTime.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TaskOTimeDataLayerMetadata)" DestinationFolder="$(TargetDir)Model\" SkipUnchangedFiles="true" />
  </Target>

</Project>
