<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskOTime.DTOs\TaskOTime.DTOs.csproj" />
    <ProjectReference Include="..\TaskOTime.AppServer\TaskOTime.AppServer.csproj" />
    <ProjectReference Include="..\TaskOTime.DataLayer\TaskOTime.DataLayer.csproj" />
    <ProjectReference Include="..\TaskOTime.ViewModel\TaskOTime.ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EntityDeploy Include="..\TaskOTime.DataLayer\Model\TaskOTime.edmx" Link="Model\TaskOTime.edmx" />
    <None Include="..\TaskOTime.DataLayer\DbGenerationScript.sql" Link="DbGenerationScript.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="CopyDataLayerMetadata" AfterTargets="Build">
    <ItemGroup>
      <TaskOTimeDataLayerMetadata Include="..\TaskOTime.DataLayer\bin\$(Configuration)\Model\TaskOTime.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TaskOTimeDataLayerMetadata)" DestinationFolder="$(TargetDir)Model\" SkipUnchangedFiles="true" />
  </Target>

</Project>
