<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>10</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
    <ProjectReference Include="..\TaskOTime.ViewModel\TaskOTime.ViewModel.vbproj" />
    <ProjectReference Include="..\TaskOTime.AppServer\TaskOTime.AppServer.csproj" />
    <ProjectReference Include="..\TaskOTime.DataLayer\TaskOTime.DataLayer.csproj" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <Target Name="CopyEntityFrameworkMetadata" AfterTargets="Build">
    <ItemGroup>
      <TaskOTimeEntityMetadata Include="$(MSBuildProjectDirectory)\..\TaskOTime.DataLayer\bin\$(Configuration)\Model\TaskOTime.csdl" />
      <TaskOTimeEntityMetadata Include="$(MSBuildProjectDirectory)\..\TaskOTime.DataLayer\bin\$(Configuration)\Model\TaskOTime.ssdl" />
      <TaskOTimeEntityMetadata Include="$(MSBuildProjectDirectory)\..\TaskOTime.DataLayer\bin\$(Configuration)\Model\TaskOTime.msl" />
    </ItemGroup>
    <Copy SourceFiles="@(TaskOTimeEntityMetadata)"
          DestinationFolder="$(OutDir)Model"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
